version: '2'
services:
  db:
    image: mariadb
    volumes:
      - ./app/tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
