version: '2'
services:
  db:
    image: mariadb
    volumes:
      - ./app/tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: 'redis:buster'
    command: redis-server
    volumes:
      - './app/tmp/redis:/data'
  web:
    build:
      context: ./app
      dockerfile: docker/Dockerfile
    volumes:
      - ./app:/app
      - ./app/tmp/bundle:/usr/local/bundle
      - ./app/tmp/.bash_history:/root/.bash_history
      - ./app/tmp/.pry_history:/root/.pry_history
    ports:
      - '3000:3000'
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_NAME: development
    depends_on:
      - db
